postgres:
  connection_string: "postgresql://martin_user:martin_password@postgis:5432/martin_db"
  # 연결 풀 최적화
  max_size: 30
  min_size: 5
  acquire_timeout: 30
  max_lifetime: 3600

# 캐시 크기 대폭 증대 (더 크게!)
cache_size_mb: 2048

# WebUI 활성화
webui: enable-for-all

# 성능 최적화를 위한 테이블별 세부 설정
tables:
  osm_polygon:
    source: public.osm_polygon
    geometry_column: way
    srid: 3857
    # 줌 레벨별 최적화
    minzoom: 5    # 너무 낮은 줌에서는 로드 안 함
    maxzoom: 21
    # 타일 크기 최적화
    buffer: 32    # 더 작은 버퍼로 성능 향상
    extent: 2048  # 더 작은 extent로 성능 향상
    # 데이터 단순화 - 필요한 속성만
    properties:
      
    
  osm_line:
    source: public.osm_line
    geometry_column: way
    srid: 3857
    minzoom: 8    # 라인도 높은 줌에서만
    maxzoom: 21
    buffer: 32    # 작은 버퍼
    extent: 2048  # 작은 extent
    

# PNG Raster functions와 Vector functions 명시적 설정
functions:
  # PNG Raster function (명시적 PNG 형식 지정)
  raster_osm_polygons:
    source: public.raster_osm_polygons
    content_type: image/png
    minzoom: 5
    maxzoom: 21
    
  # Smart Mode용 simplified vector functions
  osm_polygon_simplified:
    source: public.osm_polygon_simplified
    minzoom: 5
    maxzoom: 15
    buffer: 64
    extent: 4096
    
  osm_line_simplified:
    source: public.osm_line_simplified
    minzoom: 8
    maxzoom: 15
    buffer: 64
    extent: 4096

# auto-publish 설정
auto_publish:
  tables: false
  functions:
    from_schemas: ["public"]
    include_patterns: [".*"]
    exclude_patterns: ["raster_.*"]  # 래스터 함수는 명시적 설정만 사용

# 성능 최적화 설정
# 타일 생성 시 간소화 레벨
simplify_geometry: true
# 병렬 처리 최적화  
pool_size: 20